apiVersion: backstage.io/v1beta3
kind: Component
metadata:
  name: car-api
  description: A simple Flask API for managing car data.
  namespace: default
  tags:
    - flask
    - api
    - cars
spec:
  type: service
  lifecycle: production
  owner: my-team
  providesApis:
    - car-api
  consumesApis:
    - some-other-api
  implementsApis:
    - car-api
  source:
    type: github
    target: https://github.com/faiz-kpit/car-api
  health:
    type: url
    target: http://localhost:5000/api/v1/cars
  parameters:
    - name: environment
      type: string
      default: production
